# Generated by Django 4.2.5 on 2023-09-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subir_archivo_e_imagen', '0002_alter_subirdumentoimagen_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subirdumentoimagen',
            table='¨files',
        ),
    ]
